# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chaitanya Pramod
# email: iam@chaitanyapramod.com
description: >- # this means to ignore newlines until "baseurl:"
  (Not so) Random words by a Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.chaitanyapramod.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ChaitanyaPramod
# github_username: ChaitanyaPramod

# For SEO plugin
twitter:
  username: ChaitanyaPramod
facebook:
  app_id: 307518499741291
  publisher: ChaitanyaPramod
  admins: ChaitanyaPramod
social:
  name: Chaitanya Pramod
  links:
    - https://twitter.com/ChaitanyaPramod
    - https://www.facebook.com/ChaitanyaPramod
    - https://www.linkedin.com/in/ChaitanyaPramod
    - https://plus.google.com/+ChaitanyaPramod
    - https://github.com/ChaitanyaPramod

google_analytics: UA-29122928-1
disqus:
  shortname: chaitanyapramod

# Build settings
markdown: kramdown
theme: minima
livereload: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
